server:
  port: 5050
---
environment: production
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/esercizioRepo2
    username: root
    password: Ilcavalierenero
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: hibernate
