spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crudTest
    username: root
    password:  Ilcavalierenero
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
---
environment: test
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
  jpa:
    database: h2
  h2:
    console:
      enabled: true